#
# FIXME::REQUIRED: set an MLflow experiment name to track pipeline executions and artifacts.
#
experiment:
  name: ""
  tracking_uri: "sqlite:///metadata/mlflow/mlruns.db"
  artifact_location: "./metadata/mlflow/mlartifacts"
#
# FIXME::OPTIONAL: Set the registry server URI. This property is especially useful if you have a
#                  registry server that’s different from the tracking server.
# model_registry:
#   uri: "sqlite:///metadata/mlflow/registry.db"
#
# FIXME::REQUIRED: Specify the training and evaluation data location.
INGEST_DATA_LOCATION: ""
#
# FIXME::OPTIONAL: Specify the format of the training and evaluation dataset. Natively supported
#                  formats are: parquet, spark_sql, delta.
# INGEST_DATA_FORMAT: parquet
#
# FIXME::OPTIONAL: Specify the scoring data location.
# INGEST_SCORING_DATA_LOCATION: ""
#
# FIXME::OPTIONAL: Specify the format of the scoring dataset. Natively supported formats are:
#                  parquet, spark_sql, delta.
# INGEST_SCORING_DATA_FORMAT: parquet
#
# FIXME::OPTIONAL: Specify the output location of the batch scoring predict step.
# SCORED_OUTPUT_DATA_LOCATION: ""
#
# FIXME::OPTIONAL: Specify the format of the scored dataset. Natively supported formats are:
#                  parquet, delta, table.
# SCORED_OUTPUT_DATA_FORMAT: parquet
